name:                go-go
version:             0.1.0.0
github:              "isovector/go-go"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/go-go#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel
- network-uri
- mtl
- text
- tagsoup
- stylist
- containers
- monoidal-containers
- rel8
- hasql
- http-client
- http-client-tls
- http-types
- bytestring
- streaming
- streaming-bytestring
- streaming-utils
- warc
- HTTP
- fgl
- hasql-streams-streaming
- hasql-transaction-io
- servant-server
- wai
- aeson
- warp
- servant-lucid
- lucid
- http-client
- wai-app-static
- async

library:
  source-dirs: src

executables:
  go-go-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-go

  spider:
    main:                Main.hs
    source-dirs:         app/Spider
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-go

tests:
  go-go-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-go
