name:                marlo
version:             0.1.0.0
github:              "isovector/go-go"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/go-go#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel
- network-uri
- mtl
- text
- tagsoup
- stylist
- containers
- rel8
- hasql
- http-client
- http-client-tls
- http-types
- bytestring
- HTTP
- servant-server
- wai
- warp
- servant-lucid
- lucid
- http-client
- wai-app-static
- async
- megaparsec
- parser-combinators
- time
- opaleye
- optparse-applicative

library:
  source-dirs: src

executables:
  search:
    main:                Main.hs
    source-dirs:         app/Search
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - marlo

  spider:
    main:                Main.hs
    source-dirs:         app/Spider
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - marlo

  index:
    main:                Main.hs
    source-dirs:         app/Index
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - marlo

  purge:
    main:                Main.hs
    source-dirs:         app/Purge
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - marlo

tests:
  go-go-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-go
